### ISSUE TITLE
Lab 3.1 Setting up dashboard doesn't detail other general settings

### ISSUE THREAD

**Issue by bradscalio** [RedHatGov/sre-workshop-dashboard#11]
[Lab 3.1 Setup Dashboard](https://github.com/RedHatGov/sre-workshop-dashboard/blob/main/workshop/content/lab3.1_monitoring.md#setup-dashboard) says to `Give the Dashboard a new name. Click 'Save' when done.` but does not indicate to keep the other general settings the default.

This may be confusing and lead to unnecessary questions especially if given remotely.

**Comment by theckang** [comment]
I clarified by saying: 'Give the Dashboard a new name.  Set `Auto-refresh` to `5s`.  Keep the other settings as their default values.  Click 'Save' when done.'

6771ff4f966f550c06cdb988e0cf24474cfb5b44
