### ISSUE TITLE
Lab 2.1 does not show up on the homeroom active modules

### ISSUE THREAD

**Issue by bradscalio** [RedHatGov/sre-workshop-dashboard#4]
The workshop modules goes Lab 1.2 to Lab 3.1 and skips Lab 2.1 Setup.

**Comment by theckang** [comment]
Yikes, sorry.  Made the change: 1f5aaece5af37ec953f3a6a744ed88726c836866

**Comment by theckang** [comment]
Created new release to include this.  We should definitely test this lab in homeroom: https://github.com/RedHatGov/sre-workshop-dashboard/releases/tag/0.1.1
