### ISSUE TITLE
Lab 2.1 oc whoami doesn't indicate who you should be

### ISSUE THREAD

**Issue by bradscalio** [RedHatGov/sre-workshop-dashboard#5]
[Lab 2.1 - Getting Started](https://github.com/RedHatGov/sre-workshop-dashboard/blob/main/workshop/content/lab2.1_setup.md#get-started) indicates to run `oc whoami` but it doesn't indicate what user you should be before running next setup step.

**Comment by theckang** [comment]
6771ff4f966f550c06cdb988e0cf24474cfb5b44
