### ISSUE TITLE
Lab 2.1 Reference to %username% is ambiguous

### ISSUE THREAD

**Issue by bradscalio** [RedHatGov/sre-workshop-dashboard#6]
[Lab 2.1 Getting Started](git clone https://github.com/RedHatGov/sre-workshop-code.git) references `oc get pods -n '%username%'-istio` but the value of %username% is a bit ambiguous if this can be replaced if Lab 2.1 will be used in the modules for the workshop ideally replace it with the actual student username value dynamically if possible.

**Comment by theckang** [comment]
`%username%` should dynamically replace with the homeroom user's name (when viewed in homeroom).  Did this not render correctly?

**Comment by bradscalio** [comment]
It did, because Lab 2.1 was missing I went to the code in github and then when going back to Lab 3.1 I see that indeed the variable is reaplaced this was just me opening issues as I go.

For the labs in homeroom the username does render, close issue with no action recommended.

**Comment by theckang** [comment]
Gotcha, yep, I forgot to include Lab 2.1 (ref: #4) in homeroom.  Closing this issue.
