### ISSUE TITLE
Lab 2.1 you are already in the user1 project

### ISSUE THREAD

**Issue by bradscalio** [RedHatGov/sre-workshop-dashboard#7]
[Lab 2,1 Getting Started`](https://github.com/RedHatGov/sre-workshop-dashboard/blob/main/workshop/content/lab2.1_setup.md#get-started) has you switch to the user project space but when logged in at the beginning you are already logged in as that user in that namespace.  it's repetitive and can be confusing however since we expect a higher level of attendee here not critical to fix.

**Comment by theckang** [comment]
I think we should have them set it just to make sure.  I'm not 100% certain it will always put the user in `user` project instead of `user-istio`

**Comment by theckang** [comment]
I clarified by saying `Switch to your user project if you aren't already using it`.  6771ff4f966f550c06cdb988e0cf24474cfb5b44

**Comment by bradscalio** [comment]
Looks good checked out code and closing with comment.
