### ISSUE TITLE
Lab 1.2 Missing writing first SLO

### ISSUE THREAD

**Issue by bradscalio** [RedHatGov/sre-workshop-dashboard#8]
[Lab 1.2 Let's Practice Building an SLO](https://github.com/RedHatGov/sre-workshop-dashboard/blob/main/workshop/content/lab1.2_slo.md#lets-practice-building-an-slo) still says `TODO`

**Comment by bradscalio** [comment]
Was this addressed or accepted as variance with no action needed?

**Comment by theckang** [comment]
@pbruszewski is working on that lab so I assigned him.

**Comment by theckang** [comment]
13bd8ba8295280c5c8039711ed83939020f2e641
