### ISSUE TITLE
Lab 2.1 Explore the application screenshot does not match output

### ISSUE THREAD

**Issue by bradscalio** [RedHatGov/sre-workshop-dashboard#9]
[Dashboard Initial View](https://drive.google.com/file/d/16uiwTRMvc1w59ILHiuhwXVI2ftqRWpfZ/view?usp=sharing) does not match that which listed in the instructions at [Lab 2.1 Explore the application](https://github.com/RedHatGov/sre-workshop-dashboard/blob/main/workshop/content/lab2.1_setup.md#explore-the-application)

**Comment by theckang** [comment]
6771ff4f966f550c06cdb988e0cf24474cfb5b44
